### ISSUE TITLE
"i18n

### ISSUE THREAD

**Issue by islndr** [pylonweb/refinerycms-menus#1]
I get "i18n: Title" where the "Reorder Pages" button is under the "Pages" tab. Also the roll down menu doesn't show up in the "Advanced Options". I've tried it with 2.0.1 and 2.0.3 and I get the same errors. I'm new to Refinery so it's completely possible that it's something I've done.

**Comment by jokklan** [comment]
Im currently working on another project, but i will soon take this project up again and complete it. Thx for the issue, i look into it :)
