### ISSUE TITLE
page labels are not customizable

### ISSUE THREAD

**Issue by passion8** [pylonweb/refinerycms-menus#17]
Resouse : Refinery::Page
`label` attributes is not customiziable . 
what is for '`page_menu[links_attributes][title_attribute]` ? 
it is sending proper POST request .
request looks like 

```
 authenticity_token:gou/z3Csi/SdMHgOmJDLy7GrCIKp7Rg/wLxChxaMcss=
 page_menu[title]:hotel_main_navigation
 page_menu[links_attributes][id]:2
 page_menu[links_attributes][label]:Experience the Resort
 .
 .
 .
ul[0][0][children][0][0][id]:menu_link_3
ul[0][0][children][0][1][id]:menu_link_4
ul[0][0][children][0][2][id]:menu_link_5
ul[0][0][children][0][3][id]:menu_link_6 
ul[0][0][children][0][4][id]:menu_link_7
ul[0][0][children][0][5][id]:menu_link_8
ul[0][0][children][0][6][id]:menu_link_9
ul[0][1][id]:menu_link_10  
ul[0][2][id]:menu_link_11
ul[0][3][id]:menu_link_12
ul[0][4][id]:menu_link_13
ul[0][5][id]:menu_link_14
```

any idea why it is occuring ? if you can suggest me something i can fix this problem . 
thanks .

**Comment by jokklan** [comment]
Im not totally sure about what you mean? Is the label attribute not stored? And what title attribute are you referring to? 
Im going on vacation tomorrow at will not be able to work for the next week, but if your problem isn't solved by then, will I do my best to help you.

**Comment by passion8** [comment]
How to assign custom labels to default refinery pages. when i try to set it,it is not working.  

After some investigation,i found that `PageMenusController` `params[page_menu]` is not taking required values. it is only accepting a single value which looks like

```
 "page_menu"=>{
"title"=>"hotel_main_navigation", 
"links_attributes"=>{
  "id"=>"14", "label"=>"icanchange", "title_attribute"=>""}}
```

So,please just tell me how do i allow `page_menu` to accept multiple values .

**Comment by passion8** [comment]
i have solved this issue . Tomorrow .. i will push it .

**Comment by jokklan** [comment]
Thank you, i look forward to see the solution :)! However as said before, can i not merge this before im home from vacation.
