### ISSUE TITLE
cant install

### ISSUE THREAD

**Issue by u007** [pylonweb/refinerycms-menus#27]
ive added:
gem 'refinerycms-page-menus', '2.0.5'
# running this failed:

rails generate refinery:menus

Could not find generator refinery:menus

**Comment by jokklan** [comment]
Hallo @u007 
We are still in the process of renaming from refinerycms-page-menus to just refinerycms-menus, and will be done with version 2.0.6. Until then use the [readme for 2.0.5](https://github.com/pylonweb/refinerycms-menus/tree/v2.0.5).
Ie. you need to use the command `rails generate refinery:page_menus` for now :).

**Comment by u007** [comment]
aa thank you :)
