### ISSUE TITLE
How can I add id or class attributes inside my view

### ISSUE THREAD

**Issue by bourroush** [pylonweb/refinerycms-menus#34]
I'm not able to display html attributes (id and or class) inside my view. I set config.html_attributes = true, and filled the infos in the admin, but nothing appear on front.

I used the previously version refinerycms-pages-menu, so maybe I need to overwrite something since I updated to the new refinerycms-menu ? 

Everything is working well except that.

Thanks !

**Comment by bourroush** [comment]
Here is my view. I may need to add :html as local, but I don't know what to put inside.
= render :partial => "/refinery/menu", :locals => { :roots => refinery_menu("top_menu") }

**Comment by jokklan** [comment]
This is actually not fully functional yet, as base RefineryCMS doens't support it, and we still use the basic `_menu.rb` partial to render the menu. But let me look into it, and will return with a solution for you shortly :)

**Comment by bourroush** [comment]
Ok thanks !

**Comment by jokklan** [comment]
If you override [views/refinery/_menu_branch.html.erb](https://github.com/refinery/refinerycms/blob/2.0.10/core/app/views/refinery/_menu_branch.html.erb) with the following https://gist.github.com/jokklan/5266484, should it work (hopefully).

Remember that you can override files with the rake command `rake refinery:override view=refinery/_menu_branch.html`

**Comment by jokklan** [comment]
Im closing this now, reopen if you still have problems :)

**Comment by bourroush** [comment]
Works like a charm ! Thank Jokklan
