### ISSUE TITLE
Menu not showed with using branch support-2.1

### ISSUE THREAD

**Issue by DriesS** [pylonweb/refinerycms-menus#38]
When I try to show the menu with this line, it renders nothing: 

```
 = Refinery::Pages::MenuPresenter.new(refinery_menu("footer"), self).to_html
```

When I inspect my refinery_menu('footer') I get this : 

[#<Refinery::MenuItem:0x007faddbb54ab0 @menu=[...], @lft=1, @menu_match=nil, @parent_id=nil, @rgt=2, @title="Dries test", @url={:controller=>"/refinery/pages", :action=>"show", :only_path=>true, :path=>["dries-test"], :id=>nil}, @original_id=1, @original_type="Refinery::Menus::MenuLink", @attributes={:lft=>1, :menu_match=>nil, :parent_id=>nil, :rgt=>2, :title=>"Dries test", :url=>{:controller=>"/refinery/pages", :action=>"show", :only_path=>true, :path=>["dries-test"], :id=>nil}, :html=>{:id=>nil, :class=>nil, :title=>"Dries test"}, :original_id=>1, :original_type=>"Refinery::Menus::MenuLink"}, @html={:id=>nil, :class=>nil, :title=>"Dries test"}>, #<Refinery::MenuItem:0x007faddbb60388 @menu=[...], @lft=3, @menu_match=nil, @parent_id=nil, @rgt=4, @title="Products", @url="http://localhost:3000/products/ta-65", @original_id=2, @original_type="Refinery::Menus::MenuLink", @attributes={:lft=>3, :menu_match=>nil, :parent_id=>nil, :rgt=>4, :title=>"Products", :url=>"http://localhost:3000/products/ta-65", :html=>{:id=>nil, :class=>nil, :title=>"Products"}, :original_id=>2, :original_type=>"Refinery::Menus::MenuLink"}, @html={:id=>nil, :class=>nil, :title=>"Products"}>]

Is the support-2.1 branch working and tested?

**Comment by DriesS** [comment]
Ok I overwrited the menu_presenter and was small issue in this one. It's fixed now. Thanks!

**Comment by jokklan** [comment]
Could you show me the fix, so i can add it to the project :)?

**Comment by DriesS** [comment]
It was fix on my personal menu presenter, with the official menu presenter of refinery it works just fine.

**Comment by jokklan** [comment]
Ok thank you :)
