### ISSUE TITLE
cant add another menu

### ISSUE THREAD

**Issue by sasharevzin** [pylonweb/refinerycms-menus#5]
tried this but still cant find footer menu :(

Refinery::PageMenus.configure do |config|
  config.new_menus = true
  config.default_menus = ['main_menu', 'footer_menu']
end

ps. server already restarted

**Comment by jokklan** [comment]
you have to run rake db:seed, or you can run this command in the rails console:

``` ruby
::Refinery::PageMenus.default_menus.each do |menu|
    ::Refinery::PageMenu.create(:title => menu.titleize, :permatitle => menu)
end
```

**Comment by jokklan** [comment]
You can now use rake tasks. See readme and 4343b2134a21e5023bfe9817a19e38432001f97b
