### ISSUE TITLE
rake db:seed doesnt work

### ISSUE THREAD

**Issue by sasharevzin** [pylonweb/refinerycms-menus#6]
gives an error: uninitialized constant Refinery::PageMenu::Engine

**Comment by sasharevzin** [comment]
should be:
Refinery::PageMenus::Engine.load_seed
and not:
Refinery::PageMenu::Engine.load_seed

when appending to seed.rb

**Comment by jokklan** [comment]
I can see that you have forked the project. Your are more than welcome to write a pull request :D!

I will begin developing on this project again in the coming week.

**Comment by sasharevzin** [comment]
ok, thanks

On Sun, May 13, 2012 at 11:59 AM, Johan
reply@reply.github.com
wrote:

> I can see that you have forked the project. Your are more than welcome to write a pull request :D!
> 
> I will begin developing on this project again in the coming week.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/pylonweb/refinerycms-page-menus/issues/6#issuecomment-5674947

## 

Thanks

**Comment by jokklan** [comment]
I think this is fixed?
